Update 2019-10-22-react-release-channels.md
reactjs/es.reactjs.org pull request #393
Opened 2020-10-04 16:26 UTC by aroundarmor

2020-10-04 17:50 UTC, alejandronanez requested changes
@aroundarmor this PR still needs a lot of work as there are many many inconsistencies in the translation, Please proof read the translation before calling it ready for review.

Thank you!

2020-10-04 22:35 UTC, alejandronanez commented
@aroundarmor I'm labeling this as `invalid` in the meantime as this translation doesn't meet the minimum quality standards we have for the translations. I happily remove this label if you decide to update this Pull Request.

Thanks for your understanding.

2020-10-05 17:59 UTC, aroundarmor commented
Hello @alejandronanez,
I would like to know more about the changes that I have to make. If you will be a little bit specific I can give it a try to resolve all the things.

2020-10-06 02:57 UTC, alejandronanez commented on content/blog/2019-10-22-react-release-channels.md
> +El Siguiente canal es un canal de presentación que pistas la rama maestra del repositorio de React. Usamos pre lanzamientos en el canal Siguiente como candidatos de lanzamiento para el Latest canal.
@aroundarmor this is one of the parts that need a better translation. If you proof read the whole document you'll find many occurrences like this one.

2020-10-06 02:57 UTC, alejandronanez commented on content/blog/2019-10-22-react-release-channels.md
> +- [**Último**](#último-canal) Es para el estable, lanzamientos de semver React. Es lo que obtienes cuando instalas React desde npm. Este es el canal que ya estás usando hoy. **Use esto para todas las
Please do not translate the #anchors, just the link text. 👍

2021-08-11 05:28 UTC, closed without merging