Translated 2014-09-03-introducing-the-jsx-specification.md to spanish
reactjs/es.reactjs.org pull request #395
Opened 2020-10-05 20:55 UTC by FLiotta

2020-10-05 21:01 UTC, FLiotta commented
@alejandronanez it doesn't let me edit reviewers to assign you

2020-10-05 22:21 UTC, carburo commented
@FLiotta Yes, don't worry. You don't need to assign a reviewer.

2020-10-05 22:47 UTC, FLiotta commented
Nice! ty :)

2020-10-08 18:02 UTC, alejandronanez commented
Thanks for the PR! 

I'll take a look at this on Saturday. 👏🏼

2020-10-30 07:45 UTC, carburo requested changes

2020-10-30 07:45 UTC, carburo commented on content/blog/2014-09-03-introducing-the-jsx-specification.md
> +title: "Introduciendo el concepto de JSX"
```suggestion
title: "Introduciendo la especificación de JSX"
```

2020-10-30 07:45 UTC, carburo commented on content/blog/2014-09-03-introducing-the-jsx-specification.md
> +También hemos visto esfuerzos similares surgir de nuestro trabajo para ser utilizado con otras librarías de maneras interesantes. En este punto React JSX es solo una de muchas implementaciones.
```suggestion
En Facebook hemos estado usando JSX por un largo tiempo. Originalmente lo introdujimos al mundo el año pasado junto con React, pero en realidad lo usábamos de otra forma anteriormente para crear nodos nativos del DOM. También hemos visto esfuerzos similares surgir de nuestro trabajo para ser utilizado con otras bibliotecas de maneras interesantes. En este punto React JSX es solo una de muchas implementaciones.
```

2020-10-30 07:45 UTC, carburo commented on content/blog/2014-09-03-introducing-the-jsx-specification.md
> +Para que sea más fácil de implementar nuevas versiones y asegurar que la sintaxis se mantenga compatible, estamos formalizando la sintaxis de JSX como un funcionamiento independiente sin ningún signi
```suggestion
Para que sea más fácil de implementar nuevas versiones y asegurar que la sintaxis se mantenga compatible, estamos formalizando la sintaxis de JSX como una especificación independiente sin ningún significado semántico. Es completamente independiente del propio React.
```

2020-10-30 07:45 UTC, carburo commented on content/blog/2014-09-03-introducing-the-jsx-specification.md
> +Lee las especificaciones ahora en <https://facebook.github.io/jsx/>.
```suggestion
Lee la especificación ahora en <https://facebook.github.io/jsx/>.
```

2020-10-30 07:45 UTC, carburo commented on content/blog/2014-09-03-introducing-the-jsx-specification.md
> +Esta no es una propuesta para estandarizarlo en ECMAScript. Es solo un documento de referencia en donde los escritores de transpiladores y los resaltadores de sintaxis puedan concordar. Esta actualme
```suggestion
Esta no es una propuesta que deba estandarizarse en ECMAScript. Es solo un documento de referencia en donde los escritores de transpiladores y los resaltadores de sintaxis puedan concordar. Está actualmente en una etapa de boceto pero probablemente continúe hasta convertirse en un documento.
```

2020-10-30 13:43 UTC, carburo approved these changes

2020-10-30 13:45 UTC, merged