Translated 2020-09-22-introducing-the-new-jsx-transform
reactjs/es.reactjs.org pull request #396
Opened 2020-10-06 19:59 UTC by MigueMartelo

Translated `2020-09-22-introducing-the-new-jsx-transform.md` #201

2020-10-06 20:37 UTC, carburo commented
Hi, @MigueMartelo thanks for your contribution and for bringing to our attention the missing ids. However, as these are out of the scope of this PR could you move it to a different one? Also, the ids shouldn't be translated (as described [here](https://github.com/reactjs/es.reactjs.org/blob/master/TRANSLATION.md#identificadores-de-los-t%C3%ADtulos)):
For example instead of: 
`## Usa HOCs para preocupaciones transversales {#usa-hocs-para-preocupaciones-transversales}`
it should be:
`## Usa HOCs para preocupaciones transversales {#use-hocs-for-cross-cutting-concerns-use-hocs-for-cross-cutting-concerns}`
as you can see here:
https://github.com/reactjs/reactjs.org/blob/master/content/docs/higher-order-components.md#use-hocs-for-cross-cutting-concerns-use-hocs-for-cross-cutting-concerns

I will try to review the rest of the PR tonight.

2020-10-06 20:53 UTC, MigueMartelo commented
Hi @carburo I don't know what happen, I only modified the .md for the post.

2020-10-07 06:19 UTC, carburo requested changes
@MigueMartelo 
No pude hacer una reseña profunda, pero si dejé algunos comentarios.
Además dejo aquí dos notas generales:
- Creo que deberíamos usar una frase más idiomática como traducción para «_under the hood_», en lugar de «bajo el capó». Quizá sea una frase común en algunas variantes regionales del español, pero aún así sería preferible una frase que resulte natural para cualquier hispanohablante.
- La traducción utiliza «usted» para la segunda persona del singular, pero como se indica en nuestra [guía de traducción](https://github.com/reactjs/es.reactjs.org/blob/master/TRANSLATION.md) decidimos usar «tú» de forma consistente en toda la documentación.

2020-10-07 06:19 UTC, carburo commented on content/blog/2020-09-22-introducing-the-new-jsx-transform.md
> +## Qué es una transformación de JSX? {#whats-a-jsx-transform}
```suggestion
## ¿Qué es una transformación de JSX? {#whats-a-jsx-transform}
```

2020-10-07 06:19 UTC, carburo commented on content/blog/2020-09-22-introducing-the-new-jsx-transform.md
> +Aunque React 17 [no tiene nuevas funciones](/blog/2020/08/10/react-v17-rc.html), brindará soporte para la nueva transformación de JSX. En este post, describiremos qué es y cómo probarlo.
Aunque el uso de «funciones» es perfectamente válido, creo que el uso de «funcionalidades» permitiría ganar en claridad sobre lo que se refiere (https://www.fundeu.es/consulta/funcionalidad-2258/).

2020-10-07 06:19 UTC, carburo commented on content/blog/2020-09-22-introducing-the-new-jsx-transform.md
> +## Qué es diferente en la nueva transformación? {#whats-different-in-the-new-transform}
```suggestion
## ¿Qué es diferente en la nueva transformación? {#whats-different-in-the-new-transform}
```

2020-10-07 15:12 UTC, MigueMartelo commented on content/blog/2020-09-22-introducing-the-new-jsx-transform.md
> +## Qué es una transformación de JSX? {#whats-a-jsx-transform}
Vale @carburo estaré trabajando ahora en la mañana en esto.

2020-10-11 03:38 UTC, carburo commented on content/blog/2020-09-22-introducing-the-new-jsx-transform.md
> +Aunque React 17 [no tiene nuevas funcionalidades](/blog/2020/08/10/react-v17-rc.html), brindará soporte para la nueva transformación de JSX. En este post, describiremos qué es y cómo probarlo.
```suggestion
Aunque React 17 [no tiene nuevas funcionalidades](/blog/2020/08/10/react-v17-rc.html), brindará soporte para la nueva transformación de JSX. En este post, describiremos qué es y cómo probarla.
```

2020-10-11 04:08 UTC, carburo requested changes
Hi @MigueMartelo. This is the full review. I left some suggestions. Let me know in case you need additional context or disagree with the suggestion.

2020-10-13 15:32 UTC, MigueMartelo commented
Hi @carburo I don't know what happen with the las commit, can you help me? In this commits I only did the changes that you suggested me.
Thank you!

2020-10-13 15:35 UTC, MigueMartelo commented
> Hi @carburo I don't know what happen with the las commit, can you help me? In this commits I only did the changes that you suggested me.
> Thank you!

Sorry, the file had a conflict and I hadn't seen.

2020-10-21 04:01 UTC, carburo approved these changes

2020-10-21 14:42 UTC, merged