2020-10-20-react-v17.md
reactjs/es.reactjs.org pull request #410
Opened 2020-11-18 01:24 UTC by FranciscoImanolSuarez

As I mentioned today, I leave you my PR of the document 2020-10-20-react-v17.md

I hope it's all okay!

My number # 201

👨‍🚀

2020-11-29 05:50 UTC, carburo requested changes
¡Hola @FranciscoImanolSuarez!
Muchas gracias por la contribución.
En la mayoría de los casos has utilizado «usted» para la segunda persona del singular. Para mantener una consistencia en la documentación, [hemos optado por utilizar «tú»](https://github.com/reactjs/es.reactjs.org/blob/master/TRANSLATION.md#usted-t%C3%BA-y-vos) en estos casos. Además dejé algunas sugerencias en algunas líneas. No dudes en preguntar cualquier duda o si necesitas más contexto sobre alguna de ellas.

2020-11-29 05:50 UTC, carburo commented on content/blog/2020-10-20-react-v17.md
> +Para habilitar las actualizaciones graduales, necesitamos realizar algunos cambios en el sistema de eventos React. React 17 es una versión importante porque estos cambios potencialmente se están romp
> React 17 es una versión importante porque estos cambios potencialmente se están rompiendo.

La traducción de _«major»_ de esta forma no parece estar muy extendida e incluso propensa a confusión. Creo que preferiblemente deberíamos usar el calco «mayor» o como hace la traducción de semver.org, el anglicismo crudo.

Por otra parte la traducción _«potentially breaking changes»_ creo que no expresa completamente el sentido de la frase original. ¿Quizá «cambios que potencialmente introduzcan rupturas» o «cambios potencialmente incompatibles» siguiendo la terminología de semver.org?

2020-11-29 05:50 UTC, carburo commented on content/blog/2020-10-20-react-v17.md
> +## Otros cambios importantes
> Otros cambios importantes
Deberíamos seguir una terminología consistente. En el caso de _breaking change_ probablemente usaríamos «cambio incompatible» siguiendo la terminología de [semver.org](https://semver.org/lang/es/).

2020-11-29 05:50 UTC, carburo commented on content/blog/2020-10-20-react-v17.md
> +### Modo concurrente (Concurrent Mode) (Experimental) {#concurrent-mode-experimental}
```suggestion
### Modo concurrente (Experimental) {#concurrent-mode-experimental}
```

2020-11-29 05:50 UTC, carburo commented on content/blog/2020-10-20-react-v17.md
> +* Limpia todos los efectos antes de ejecutar los siguientes efectos. ([@bvaughn](https://github.com/bvaughn) en [#17947](https://github.com/facebook/react/pull/17947))
>  Limpia todos los efectos antes de ejecutar los siguientes efectos. ([@bvaughn](https://github.com/bvaughn) en [#17947](https://github.com/facebook/react/pull/17947))

Aunque los mensajes de los commits en inglés están escritos en imperativo, la traducción creo que se beneficiaría del infinitivo para una mayor naturalidad.

2020-12-03 02:57 UTC, FranciscoImanolSuarez commented
Ow mucho Feedback, mañana empezare a corregir lo que me pides, disculpa que no atendi antes estaba estudiando para un Examen, pero mañana ya empiezo a corregir  ! Muchas gracias por tu FeedBack!

2021-08-05 17:46 UTC, closed without merging