Translate 2020-12-21-data-fetching-with-react-server-components.md
reactjs/es.reactjs.org pull request #426
Opened 2021-02-01 15:08 UTC by pedabraham

Hello 👋! I've translated the blog post `2020-12-21-data-fetching-with-react-server-components.md`

As I mention in #201

2021-10-02 20:55 UTC, Carababusha reviewed
Revisado con propuesta de traducción para "Zero-Bundle-Size React Server Components" y "React Server Components", y cambios relacionados con esto.

2021-10-02 20:55 UTC, Carababusha commented on content/blog/2020-12-21-data-fetching-with-react-server-components.md
> +title: "Introduciendo los Zero-Bundle-Size React Server Components"
Tras ver el vídeo que explica en lo que consiste este cambio, sugeriría traducirlo así:
title: "Introduciendo componentes de React en servidor con paquetes de tamaño cero"

2021-10-02 20:55 UTC, Carababusha commented on content/blog/2020-12-21-data-fetching-with-react-server-components.md
> +2020 ha sido un año bastante largo. Mientras llega a su fin, queremos compartirte una actualización especial de temporada, de nuestra investigación sobre los zero-bundle-size **React Server Component
Sugerencia para esta línea si se acepta el cambio sugerido arriba para traducir "Zero-Bundle-Size React Server Components":
2020 ha sido un año bastante largo. Mientras llega a su fin, queremos compartirte una actualización especial de temporada, de nuestra investigación sobre los **componentes de React en servidor**  con paquetes de tamaño cero.

2021-10-02 20:55 UTC, Carababusha commented on content/blog/2020-12-21-data-fetching-with-react-server-components.md
> +Para introducir los React Server Components, hemos preparado una charla y una demostración. Si gustas, puedes revisarlas durante las vacaciones decembrinas, o después cuando el trabajo se reanude en
Sugerencia acorde con las líneas anteriores:
Para introducir los componentes de React en servidor, hemos preparado una charla y una demostración. Si gustas, puedes revisarlas durante las vacaciones decembrinas, o después cuando el trabajo se reanude en el año nuevo.

2021-10-02 20:55 UTC, Carababusha commented on content/blog/2020-12-21-data-fetching-with-react-server-components.md
> +**Los React Server Components siguen en investigación y desarrollo.** Estamos compartiendo este trabajo con el espíritu de transparencia y para obtener retroalimentación inicial por parte de la comun
Versión propuesta en consonancia con las líneas anteriores, más un acento que se había escapado:
**Los componentes de React en servidor siguen en investigación y desarrollo.** Estamos compartiendo este trabajo con el espíritu de transparencia y para obtener retroalimentación inicial por parte de la comunidad de React. Habrá suficiente tiempo para eso, por lo que **¡no sientas que necesitas ponerte al corriente ahora mismo!**

2021-10-02 20:55 UTC, Carababusha commented on content/blog/2020-12-21-data-fetching-with-react-server-components.md
> +1. **Mira la charla** para aprender sobre los React Server Components y ver la demostración.
Cambio en consonancia con las líneas anteriores:
**Mira la charla** para aprender sobre los componentes de React en servidor y ver la demostración.

2021-10-02 20:55 UTC, Carababusha commented on content/blog/2020-12-21-data-fetching-with-react-server-components.md
> +2. **[Clona la demostración](http://github.com/reactjs/server-components-demo)** para que juegues con los React Server Components en tu computadora.
Propuesta acorde con los casos anteriores y cambio sintáctico para evitar repetir "en" tan seguido:
**[Clona la demostración](http://github.com/reactjs/server-components-demo)** para poder jugar en tu computadora con los componentes de React en servidor.

2021-10-03 13:31 UTC, carburo requested changes
¡Hola @pedabraham! Disculpa por la significativa demora en revisar este artículo. Pensé hacerlo cuando se abrió el PR y luego se fue de mi radar. Estoy de acuerdo en principio con la sugerencia de @Carababusha de traducir el término de React Server Componentes y Zero-Bundle-Size. No tengo propuestas que suenen más naturales en español, por lo que podemos proceder con estas o comparar con otra alterntiva que tengas.

2021-10-03 13:31 UTC, carburo commented on content/blog/2020-12-21-data-fetching-with-react-server-components.md
> +**Los React Server Components siguen en investigación y desarrollo.** Estamos compartiendo este trabajo con el espíritu de transparencia y para obtener retroalimentación inicial por parte de la comun
```suggestion
**Los React Server Components siguen en investigación y desarrollo.** Estamos compartiendo este trabajo con el espíritu de transparencia y para obtener retroalimentación inicial por parte de la comunidad de React. Habrá suficiente tiempo para eso, por lo que **¡no sientas que necesitas ponerte al corriente ahora mismo!**
```

2021-10-03 16:17 UTC, pedabraham commented
¡Hola @Carababusha y @carburo!
Muchas gracias por revisar la traducción. Me parece bien el termino sugerido, por lo que ya realicé los cambios. También cambie el typo encontrado.

2021-10-03 16:23 UTC, pedabraham commented
!Hola @carburo!
También me pregunto si el pr puede ser válido para tener la etiqueta 'hacktoberfest-accepted'

2021-10-04 00:30 UTC, carburo commented
> También me pregunto si el pr puede ser válido para tener la etiqueta 'hacktoberfest-accepted'

Sure

2021-10-04 00:31 UTC, carburo approved these changes

2021-10-04 00:32 UTC, merged