Update 2021-06-08-the-plan-for-react-18.md
reactjs/es.reactjs.org pull request #464
Opened 2021-06-19 13:16 UTC by yepes

2021-10-03 13:46 UTC, carburo requested changes
¡Hola, @yepes! Disculpa la tardanza en la revisión. He hecho algunas sugerencias revirtiendo algunos de los cambios; ya sea porque desde mi punto de vista no representan una mejora obvia al texto anterior o bien porque el texto existente resulta más fiel al original en inglés.

2021-10-03 13:46 UTC, carburo commented on content/blog/2021-06-08-the-plan-for-react-18.md
> +Estas características son posibles gracias a un nuevo mecanismo de inclusión optativa que estamos agregando en React 18. Se llama “renderizado concurrente” y permite a React preparar múltiples versio
```suggestion
Estas características son posibles gracias a un nuevo mecanismo de suscripción que estamos agregando en React 18. Se llama “renderizado concurrente” y permite a React preparar múltiples versiones de la interfaz de usuario al mismo tiempo. Este cambio se produce principalmente entre bastidores, pero abre nuevas posibilidades para mejorar el rendimiento real y percibido de su aplicación.
```

2021-10-03 13:46 UTC, carburo commented on content/blog/2021-06-08-the-plan-for-react-18.md
> +Si ha estado siguiendo nuestra investigación sobre el futuro de React (¡no esperamos que lo hagas!), es posible que haya oído hablar de algo llamado “modo concurrente” que podría romper su aplicación
```suggestion
Si ha estado siguiendo nuestra investigación sobre el futuro de React (¡no esperamos que lo hagas!), es posible que haya oído hablar de algo llamado “modo concurrente” que podría romper su aplicación. En respuesta a estos comentarios de la comunidad, hemos rediseñado la estrategia de actualización para una adopción gradual. En lugar de un “modo” de todo o nada, el renderizado concurrente solo se habilitará para las actualizaciones activadas por una de las nuevas funciones. En la práctica, esto significa **que podrá adoptar React 18 sin reescribir y probar las nuevas funciones a su propio ritmo.**
```

2021-10-03 13:46 UTC, carburo commented on content/blog/2021-06-08-the-plan-for-react-18.md
> +Estamos probando algo nuevo para esta versión: hemos invitado a un grupo de expertos, desarrolladores, autores de librerías y educadores de toda la comunidad de React para participar en nuestro [Reac
```suggestion
Estamos probando algo nuevo para esta versión: hemos invitado a un panel de expertos, desarrolladores, autores de librerías y educadores de toda la comunidad de React para participar en nuestro [React 18 Working Group](https://github.com/reactwg/react-18) para proporcionar comentarios, hacer preguntas y colaborar en el lanzamiento. No pudimos invitar a todos los que queríamos a este pequeño grupo inicial, pero si este experimento funciona, ¡esperamos que haya más en el futuro!
```

2021-10-03 13:46 UTC, carburo commented on content/blog/2021-06-08-the-plan-for-react-18.md
> +Debido a que esperamos un aumento inicial de interés en el Working Group, solo los miembros invitados podrán crear o comentar en los hilos. Sin embargo, los hilos son completamente públicos, por lo q
```suggestion
Debido a que esperamos un aumento inicial de interés en el Working Group, solo los miembros invitados podrán crear o comentar en los hilos. Sin embargo, los hilos son completamente visibles para el público, por lo que todos tienen acceso a la misma información. Creemos que este es un buen compromiso entre crear un entorno productivo para los miembros del grupo de trabajo y, al mismo tiempo, mantener la transparencia con la comunidad en general.
```

2021-11-22 14:56 UTC, yepes commented
Hola @carburo , yo tampoco había visto esto. Lo acabo de aceptar ;)

2021-11-22 15:50 UTC, carburo commented
Hola! Sí, aun procede. Lo mezclaré entonces con las sugerencias añadidas.

2021-11-22 15:51 UTC, merged