traducción al español de la sección  react-dom/render
reactjs/es.reactjs.org pull request #561
Opened 2022-10-10 21:21 UTC by fabianchoxD

Hola, revisé el archivo de contribuciones y realizo mi aporte de traducción de la sección react-dom/render

déjame saber si están conforme con la traducción o requieres que realice ajustes.

Muchas gracias 😄

2022-10-29 05:53 UTC, carburo requested changes
¡Hola, @abianchoxD! ¡Muchas gracias por tu contribución!
Te he dejado algunos comentarios y sugerencias. Revísalos y aplícalos si estás de acuerdo con ellos. En el caso contrarios déjanos tu comentario.

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +Una aplicación totalmente construida con React usualmente tendrá sólo un llamado a `render` con su componente raíz "root". Una página que utiliza "sprinkles" de React para partes de la página puede t
```suggestion
Una aplicación totalmente construida con React tendrá usualmente una sola llamada a `render` con su componente raíz. Una página que utiliza React para partes de la página puede tener tantas llamadas a `render` como sean necesarias.
```

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +[Vea los ejemplos anteriores.](#usage)
```suggestion
[Mira los ejemplos anteriores.](#usage)
```

https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#usted-t%C3%BA-y-vos

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +* `reactNode`: Un *React node* que tu quieras mostrar. Por lo general se trata de un fragmento o pieza de JSX `<App />`, pero también puedes pasar un elemento de React "React element" construido con
```suggestion
* `reactNode`: Un *nodo de React* que quieras mostrar. Por lo general se trata de una pieza de JSX como `<App />`, pero también puedes pasar un elemento de React construido con [`createElement()`](/apis/react/createElement), un _string_, un número, `null`, o `undefined`.
```

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +* `domNode`: Un [elemento del DOM.](https://developer.mozilla.org/en-US/docs/Web/API/Element) React mostrará el `reactNode` que tú pases dentro de este elemento del DOM. Desde este momento, React adm
```suggestion
* `domNode`: Un [elemento del DOM.](https://developer.mozilla.org/en-US/docs/Web/API/Element) React mostrará el `reactNode` que pases dentro de este elemento del DOM. Desde este momento, React administrará el DOM dentro de `domNode` y lo actualizará cuando tu árbol de React cambie.
```

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +* **Opcional** `callback`: Una función. Si se pasa, React la llamará luego de que tu componente sea colocado dentro del DOM.
```suggestion
* `callback` **opcional**: Una función. Si se pasa, React la llamará luego de que tu componente sea colocado dentro del DOM.
```

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +#### Retorno - Returns {/*returns*/}
```suggestion
#### Retorno {/*returns*/}
```

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +`render` Por lo general retorna `null`. Sin embargo, si el `reactNode` que pasas es de tipo *class component*, entonces este retornará una instancia de ese componente.
```suggestion
`render` Por lo general retorna `null`. Sin embargo, si el `reactNode` que pasas es un *component de clase*, entonces retornará una instancia de ese componente.
```

https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#traducciones-comunes

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +* La primer ver que llamas a `render`, React limpiará todo el HTML contenido existente dentro del `domNode` antes de renderizar el componente de React dentro de este. Si tu `domNode` contiene HTML ge
```suggestion
* La primera vez que llamas a `render`, React limpiará todo el contenido HTML existente dentro del `domNode` antes de renderizar el componente de React dentro de este. Si tu `domNode` contiene HTML generado por React en el servidor o durante la compilación, usa en su lugar [`hydrate()`](/apis/react-dom/hydrate), ya que este adjunta los manejadores de eventos al HTML existente.
```

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +* Si llamas a `render` en el mismo `domNode` mas de una vez, React actualizará el DOM según sea necesario para reflear el mas reciente JSX que hayas pasado. React decidirá que partes del DOM pueden s
```suggestion
* Si llamas a `render` en el mismo `domNode` más de una vez, React actualizará el DOM según sea necesario para reflejar el JSX más reciente que hayas pasado. React decidirá qué partes del DOM se pueden reutilizar y cuáles necesitan ser recreadas ["haciendo una comparación"](/learn/preserving-and-resetting-state) con el árbol previamente renderizado. Llamar de nuevo a `render` en el mismo `domNode` es similar a llamar a la función [`set` ](/apis/react/useState#setstate) en el componente raíz: React evita actualizaciones innecesarias del DOM.
```

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +* Si tu aplicación está totalmente construida con React, es probable que sólo tengas un llamado a `render` en tu aplicación. (Si usas un framework, éste puede hacer el llamado por ti.) Cuando quieras
```suggestion
* Si tu aplicación está totalmente construida con React, es probable que tengas una sola llamada a `render` en tu aplicación. (Si usas un framework, puede que haga esta llamada por ti.) Cuando quieras renderizar un fragmento de JSX en un lugar diferente del árbol del DOM que no sea hijo de tu componente (por ejemplo, un modal o un _tooltip_), usa [`createPortal`](/apis/react-dom/createPortal) en lugar de `render`.
```

Para mantener la consistencia con la traducción de _«call»_ en este tipo de contextos en las demás páginas de la documentación deberíamos usar «llamada».

2022-10-29 05:53 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +`render` renderiza una pieza de [JSX](/learn/writing-markup-with-jsx) ("React node") en un nodo del DOM del navegador.
```suggestion
`render` renderiza una pieza de [JSX](/learn/writing-markup-with-jsx) ("nodo de React") en un nodo del DOM del navegador.
```
Está bien traducir términos técnicos siempre que haya traducciones «naturales» en español.

2022-10-29 15:49 UTC, fabianchoxD commented on beta/src/content/apis/react-dom/render.md
> +### Renderiza el componente raíz "Root component" {/*rendering-the-root-component*/}
quería dejar la traducción original por si alguien busca cómo se llama en INgles.. pero así está bien tambien jeje.

2022-10-29 15:58 UTC, fabianchoxD commented on beta/src/content/apis/react-dom/render.md
> +### Actualizando el árbol renderizado {/*updating-the-rendered-tree*/}
Updating no conjuga la palabra ¿? por eso pensaba que quedaba mejor Actualizando y no el verbo en infinitivo.

2022-10-29 16:01 UTC, fabianchoxD commented on beta/src/content/apis/react-dom/render.md
> +No es muy común llamar a `render` varias veces. Por lo general [actualizarás el estado](/apis/react/useState) dentro de uno de los componentes.
en ese caso te propongo mejor:  "Por lo general lo que debes hacer es" [ actualizar....

¿Qué opinas?.

2022-10-29 16:38 UTC, carburo commented on beta/src/content/apis/react-dom/render.md
> +No es muy común llamar a `render` varias veces. Por lo general [actualizarás el estado](/apis/react/useState) dentro de uno de los componentes.
De acuerdo.

2022-10-30 00:02 UTC, carburo approved these changes
¡Muchas gracias!

2022-10-30 00:05 UTC, merged