Translate react apis createContext ( beta docs )
reactjs/es.reactjs.org pull request #562
Opened 2022-10-10 23:48 UTC by Nicolas-alt

2022-10-30 04:29 UTC, carburo requested changes
¡Hola, @Nicolas-alt! Gracias por tu contribución. Te dejé algunos comentarios para que los revises.

2022-10-30 04:29 UTC, carburo commented on beta/src/content/apis/react/createContext.md
> +### Creando un contexto {/*creating-context*/}
```suggestion
### Crear un contexto {/*creating-context*/}
```

https://github.com/reactjs/reactjs.org-translation/blob/main/langs/es.json

2022-10-30 04:29 UTC, carburo commented on beta/src/content/apis/react/createContext.md
> +De forma predeterminada, los valores que reciben serán los <CodeStep step={3}>valores predeterminados</CodeStep> que se han especificado al crear los contextos. Sin embargo, esto no es útil porque lo
```suggestion
De forma predeterminada, los valores que reciben serán los <CodeStep step={3}>valores predeterminados</CodeStep> que se han especificado al crear los contextos. Sin embargo, esto por sí mismo no es útil porque los valores predeterminados nunca cambian.
```
Estoy siempre a favor de no traducir literalmente, pero creo que aquí se pierde un poco el sentido de la frase original al omitir esta parte que «por sí mismo» da a entender: es útil, pero solo cuando se combina con algo más (los valores dinámicos que se le puede pasar).

2022-10-30 04:29 UTC, carburo commented on beta/src/content/apis/react/createContext.md
> +[Aprende más sobre leer y proporcionar un contexto, ver más ejemplos.](/apis/react/useContext)
```suggestion
[Aprende más sobre leer y proporcionar un contexto, y consulta ejemplos.](/apis/react/useContext)
```

2022-10-30 04:29 UTC, carburo commented on beta/src/content/apis/react/createContext.md
> +* `value`: El valor que desees pasar a todos los componentes que leen este contexto dentro de este proveedor, sin importar cuán profundo sea. El valor de contexto puede ser de cualquier tipo. Un comp
```suggestion
* `value`: El valor que desees pasar a todos los componentes que leen este contexto dentro de este proveedor, sin importar cuán profundo sea. El valor de contexto puede ser de cualquier tipo. Un componente que llama a [`useContext(SomeContext)`](/apis/react/useContext) dentro del proveedor recibe el valor (`value`) del proveedor de contexto correspondiente más interno que se encuentra arriba.
```
Aquí `value` está haciendo a la prop que se está describiendo.

2022-10-30 04:29 UTC, carburo commented on beta/src/content/apis/react/createContext.md
> +* `children`: Una función. React llamará a la función que pase con el valor de contexto actual determinado por el mismo algoritmo que [`useContext()`](/apis/react/useContext) y generará el resultado
```suggestion
* `children`: Una función. React llamará a la función que pases con el valor de contexto actual determinado por el mismo algoritmo que [`useContext()`](/apis/react/useContext) y renderizará el resultado que devuelves de esta función. React también volverá a ejecutar esta función y actualizará la interfaz de usuario siempre que el contexto pasado desde los componentes principales haya cambiado.
```

2022-10-30 04:29 UTC, carburo commented on beta/src/content/apis/react/createContext.md
> +Para hacer que el contexto cambie con el tiempo, [agrega componentes de estado y ajusta un proveedor de contexto.](/apis/react/useContext#updating-data-passed-via-context)
```suggestion
Para hacer que el contexto cambie con el tiempo, [agrega estado y envuelve los componentes en un proveedor de contexto.](/apis/react/useContext#updating-data-passed-via-context)
```

2022-11-02 02:42 UTC, Nicolas-alt commented
> ¡Hola, @Nicolas-alt! Gracias por tu contribución. Te dejé algunos comentarios para que los revises.

Ya quedaron los arreglos @carburo

2022-11-02 02:46 UTC, carburo approved these changes
¡Muchas gracias! :rocket:

2022-11-02 02:46 UTC, merged