translation
reactjs/es.reactjs.org pull request #564
Opened 2022-10-11 14:30 UTC by Waxer59

#500

2022-11-09 19:15 UTC, Vicenciomf1 requested changes
Hola @Waxer59 , ¿qué tal va todo? Primero que todo, ¡muchas gracias por tu aporte! Acabo de revisar tu PR, y agregué algunas sugerencias para que podamos agilizar el merge de tu rama. Si tienes cualquier consulta, no dudes en escribirme :) ¡Saludos!

2022-11-09 19:15 UTC, Vicenciomf1 commented on beta/src/content/apis/react/Fragment.md
> +- React no [restablece el estado](/learn/preserving-and-resetting-state) cuando vas desde renderizar `<><Child /></>` a `[<Child />]` o atrás, o cuando vas desde renderizar `<><Child /></>` a`<Child
```suggestion
- React no [restablece el estado](/learn/preserving-and-resetting-state) cuando renderizas desde un `<><Child /></>` a un `[<Child />]` y viceversa, o cuando renderizas desde un `<><Child /></>` a un `<Child />` y viceversa. Ten en cuenta de que esto sólo funciona a un nivel de profundidad: por ejemplo, ir desde un `<><><Child /></></>` a un `<Child />` restablece el estado. Échale un ojo a la sintaxis en detalle [aquí.](https://gist.github.com/clemmy/b3ef00f9507909429d8aa0d3ee4f986b)
```

2022-11-10 02:43 UTC, Waxer59 commented
Hola, muchas gracias por la revisión, ya realize todos los cambios que me mencionaste

2022-11-10 04:03 UTC, Vicenciomf1 approved these changes

2022-11-10 04:04 UTC, Vicenciomf1 commented
> Hola, muchas gracias por la revisión, ya realicé todos los cambios que me mencionaste

¡Gracias a ti @Waxer59! ¡Ten una buena semana!

2022-11-10 04:04 UTC, merged