added translation for state a components memory
reactjs/es.reactjs.org pull request #586
Opened 2022-10-19 01:26 UTC by samarjaffal

#500

2022-10-28 23:53 UTC, Vicenciomf1 requested changes
Hola @samarjaffal! Muchas gracias por tu aporte! Agregué y cambié algunas cosas para mantener el estilo de escritura de los capítulos anteriores de esta documentación y de la anterior, además de algunas cosas frecuentes que suele corregir @carburo, así podemos agilizar el merge de tu PR.
Pd: Vi tu presentación en la miduconf y fue muy inspiracional, gracias por los consejos.

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +Es posible que hayas notado que la llamada `useState` no recibe ninguna información sobre *a qué* variable de estado se refiere. No hay un "identificador" que se pase a `useState`, entonces, ¿cómo sa
* Frase: "Es posible que hayas notado que la llamada `useState` no recibe"
   * Sugerencia: "Es posible que hayas notado que la llamada a `useState` no recibe"

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +Internamente, React mantiene una matriz de pares de estados para cada componente. También mantiene el índice de par actual, el cual se establece en `0` antes de ser renderizado. Cada vez que llamamos
1. Convención de [traducción común](https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#traducciones-comunes)
   * Frase: "Internamente, React mantiene una matriz de pares de estados para cada componente."
   * Sugerencia: "Internamente, React mantiene un _array_ de pares de estados para cada componente."
   * Razón: Así mantenemos la consistencia con los usos anteriores en este capítulo, y los capítulos anteriores en la documentación.

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
>          by {sculpture.artist}
1. Falta traducir la preposición
   * Frase: "by"
   * Sugerencia: "por"
   * Razón: Así mantenemos la traducción de strings al español de manera consistente (la idea es mantenerlo en inglés, o en español, pero no ambas).

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
>      header: `${sculpture.name} by ${sculpture.artist}`,
1. Falta traducir la preposición
   * Frase: "by"
   * Sugerencia: "por"
   * Razón: Así mantenemos la traducción de strings al español de manera consistente (la idea es mantenerlo en inglés, o en español, pero no ambas).

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
>          by {sculpture.artist}
1. Falta traducir la preposición
   * Frase: "by"
   * Sugerencia: "por"
   * Razón: Así mantenemos la traducción de strings al español de manera consistente (la idea es mantenerlo en inglés, o en español, pero no ambas).

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +También observemos cómo el componente de `Página` no "sabe" nada sobre el estado del componente `Galería` o incluso si tiene algún estado. A diferencia de las props, **el estado es totalmente privado
1. Mantener consistencia con el embed del CodeSandBox
   * Frase: "cómo el componente de `Página` no "sabe" nada sobre el estado del componente `Galería`"
   * Sugerencia: "cómo el componente de la página `Page` no "sabe" nada sobre el estado del componente de la galería `Galery`"
   * Razón: De tal manera podemos mantener la consistencia y hacer referencia a lo mismo tanto en la explicación como en el _CodeSandBox_ a lo largo del capítulo (En el código no fue traducido el nombre del componente).

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +* Los Hooks se importan de la siguiente manera: deben llamarse incondicionalmente. Llamar Hooks, incluido `useState`, solo es válido en el nivel superior de un componente u otro Hook.
1. Parafraseo
   * Frase: "Los Hooks se importan de la siguiente manera: deben llamarse incondicionalmente. Llamar Hooks, incluido `useState`, solo es válido en el nivel superior de un componente u otro Hook.""
   * Sugerencia: "Evita llamar a Hooks de manera anidada (por ejemplo, dentro de bucles, condicionales o declaraciones de funciones anidadas). Llamar a Hooks, incluyendo al `useState`, solo es válido en el nivel superior de un componente u otro Hook."
   * Razón: La traducción directa pierde algo de significado, por lo que podemos cambiar algunas palabras para mantenerlo en español.

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  // así que crea un arreglo de dos posiciones y guárdalo.
1. Convención de [traducción común](https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#traducciones-comunes)
   * Frase: "crea un arreglo"
   * Sugerencia: "crea un _array_"
   * Razón: Así mantenemos la consistencia con los usos anteriores y posteriores en este capítulo, y los capítulos anteriores en la documentación.

2022-10-28 23:53 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +* El Hook `useState` retorna un arreglo de dos valores: el estado actual y la función para actualizarlo.
1. Convención de [traducción común](https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#traducciones-comunes)
   * Frase: "retorna un arreglo"
   * Sugerencia: "retorna un _array_"
   * Razón: Así mantenemos la consistencia con los usos anteriores y posteriores en este capítulo, y los capítulos anteriores en la documentación.

2022-10-29 22:58 UTC, Vicenciomf1 requested changes

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'Esta enorme flor plateada (75 pies o 23 m) se encuentra en Buenos Aires. Está diseñado para moverse, cerrando sus pétalos por la tarde o cuando soplan fuertes vientos y abriéndolos po
```suggestion
  description: 'Wilson era conocido por su preocupación por la igualdad y la justicia social, así como por las cualidades esenciales y espirituales de la humanidad. Esta enorme pieza de bronce (de 7 pies o 2,13 metros) representa lo que él describió como "una presencia negra simbólica impregnada de un sentido de humanidad universal".',
```
Razón: Este par key-value está desfasado, la descripción corresponde a la key anterior (la description de la Floraris Genérica).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'Esta enorme flor plateada (75 pies o 23 m) se encuentra en Buenos Aires. Está diseñado para moverse, cerrando sus pétalos por la tarde o cuando soplan fuertes vientos y abriéndolos po
```suggestion
  description: 'Wilson era conocido por su preocupación por la igualdad y la justicia social, así como por las cualidades esenciales y espirituales de la humanidad. Esta enorme pieza de bronce (de 7 pies o 2,13 metros) representa lo que él describió como "una presencia negra simbólica impregnada de un sentido de humanidad universal".',
```
Razón: Este par key-value está desfasado, la descripción corresponde a la key anterior (la description de la Floraris Genérica).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'Esta enorme flor plateada (75 pies o 23 m) se encuentra en Buenos Aires. Está diseñado para moverse, cerrando sus pétalos por la tarde o cuando soplan fuertes vientos y abriéndolos po
```suggestion
  description: 'Wilson era conocido por su preocupación por la igualdad y la justicia social, así como por las cualidades esenciales y espirituales de la humanidad. Esta enorme pieza de bronce (de 7 pies o 2,13 metros) representa lo que él describió como "una presencia negra simbólica impregnada de un sentido de humanidad universal".',
```
Razón: Este par key-value está desfasado, la descripción corresponde a la key anterior (la description de la Floraris Genérica).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'Esta enorme flor plateada (75 pies o 23 m) se encuentra en Buenos Aires. Está diseñado para moverse, cerrando sus pétalos por la tarde o cuando soplan fuertes vientos y abriéndolos po
```suggestion
  description: 'Wilson era conocido por su preocupación por la igualdad y la justicia social, así como por las cualidades esenciales y espirituales de la humanidad. Esta enorme pieza de bronce (de 7 pies o 2,13 metros) representa lo que él describió como "una presencia negra simbólica impregnada de un sentido de humanidad universal".',
```
Razón: Este par key-value está desfasado, la descripción corresponde a la key anterior (la description de la Floraris Genérica).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'Esta enorme flor plateada (75 pies o 23 m) se encuentra en Buenos Aires. Está diseñado para moverse, cerrando sus pétalos por la tarde o cuando soplan fuertes vientos y abriéndolos po
```suggestion
  description: 'Wilson era conocido por su preocupación por la igualdad y la justicia social, así como por las cualidades esenciales y espirituales de la humanidad. Esta enorme pieza de bronce (de 7 pies o 2,13 metros) representa lo que él describió como "una presencia negra simbólica impregnada de un sentido de humanidad universal".',
```
Razón: Este par key-value está desfasado, la descripción corresponde a la key anterior (la description de la Floraris Genérica).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'Esta enorme flor plateada (75 pies o 23 m) se encuentra en Buenos Aires. Está diseñado para moverse, cerrando sus pétalos por la tarde o cuando soplan fuertes vientos y abriéndolos po
```suggestion
  description: 'Wilson era conocido por su preocupación por la igualdad y la justicia social, así como por las cualidades esenciales y espirituales de la humanidad. Esta enorme pieza de bronce (de 7 pies o 2,13 metros) representa lo que él describió como "una presencia negra simbólica impregnada de un sentido de humanidad universal".',
```
Razón: Este par key-value está desfasado, la descripción corresponde a la key anterior (la description de la Floraris Genérica).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'Esta enorme flor plateada (75 pies o 23 m) se encuentra en Buenos Aires. Está diseñado para moverse, cerrando sus pétalos por la tarde o cuando soplan fuertes vientos y abriéndolos po
```suggestion
  description: 'Wilson era conocido por su preocupación por la igualdad y la justicia social, así como por las cualidades esenciales y espirituales de la humanidad. Esta enorme pieza de bronce (de 7 pies o 2,13 metros) representa lo que él describió como "una presencia negra simbólica impregnada de un sentido de humanidad universal".',
```
Razón: Este par key-value está desfasado, la descripción corresponde a la key anterior (la description de la Floraris Genérica).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'SShettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente ta
```suggestion
  description: 'Shettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente tanto abstracta como figurativamente, desafiando la gravedad, y una "fina síntesis de materiales inverosímiles.',
```
Razón: Corregido un typo (Doble S), y una coma para mejorar cohesión (mantiene el sujeto, que es la descripción de las obras).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'SShettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente ta
```suggestion
  description: 'Shettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente tanto abstracta como figurativamente, desafiando la gravedad, y una "fina síntesis de materiales inverosímiles.',
```
Razón: Corregido un typo (Doble S), y una coma para mejorar cohesión (mantiene el sujeto, que es la descripción de las obras).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'SShettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente ta
```suggestion
  description: 'Shettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente tanto abstracta como figurativamente, desafiando la gravedad, y una "fina síntesis de materiales inverosímiles.',
```
Razón: Corregido un typo (Doble S), y una coma para mejorar cohesión (mantiene el sujeto, que es la descripción de las obras).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'SShettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente ta
```suggestion
  description: 'Shettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente tanto abstracta como figurativamente, desafiando la gravedad, y una "fina síntesis de materiales inverosímiles.',
```
Razón: Corregido un typo (Doble S), y una coma para mejorar cohesión (mantiene el sujeto, que es la descripción de las obras).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'SShettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente ta
```suggestion
  description: 'Shettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente tanto abstracta como figurativamente, desafiando la gravedad, y una "fina síntesis de materiales inverosímiles.',
```
Razón: Corregido un typo (Doble S), y una coma para mejorar cohesión (mantiene el sujeto, que es la descripción de las obras).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'SShettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente ta
```suggestion
  description: 'Shettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente tanto abstracta como figurativamente, desafiando la gravedad, y una "fina síntesis de materiales inverosímiles.',
```
Razón: Corregido un typo (Doble S), y una coma para mejorar cohesión (mantiene el sujeto, que es la descripción de las obras).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +  description: 'SShettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente ta
```suggestion
  description: 'Shettar fusiona lo tradicional y lo moderno, lo natural y lo industrial. Su arte se centra en la relación entre el hombre y la naturaleza. Su trabajo fue descrito como convincente tanto abstracta como figurativamente, desafiando la gravedad, y una "fina síntesis de materiales inverosímiles.',
```
Razón: Corregido un typo (Doble S), y una coma para mejorar cohesión (mantiene el sujeto, que es la descripción de las obras).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +2. Una **función que setea el estado** para actualizar la variable y provocar que React renderice el componente nuevamente.
El único contenido ya publicado que causaría conflicto para dejarlo como _settear_, sería [este capítulo](https://beta.es.reactjs.org/learn/referencing-values-with-refs)

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +## Agregando una variable de estado {/*adding-a-state-variable*/}
```suggestion
## Agregar una variable de estado {/*adding-a-state-variable*/}
```
La [traducción directa del gerundio](https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#el-gerundio) con función sustantiva en los títulos podría perder significado, por eso es recomendado utilizar un infinitivo (Agregando->Agregar).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +## Colocando múltiples variables de estado a un componente {/*giving-a-component-multiple-state-variables*/}
```suggestion
## Colocar múltiples variables de estado a un componente {/*giving-a-component-multiple-state-variables*/}
```
La [traducción directa del gerundio](https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#el-gerundio) con función sustantiva en los títulos podría perder significado, por eso es recomendado utilizar un infinitivo (Colocando->Colocar, dar, asignar).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +Es una buena idea tener múltiples variables de estado si no se encuentran relacionadas entre sí, como `index` y `showMore` en este ejemplo. Pero si encontramso que a menudo cambiamos dos variables de
```suggestion
Es una buena idea tener múltiples variables de estado si no se encuentran relacionadas entre sí, como `index` y `showMore` en este ejemplo. Pero si encontramso que a menudo cambiamos dos variables de estado juntas, podría ser mejor combinarlas en una sola. Por ejemplo, si tenemos un formulario con muchos campos, es más conveniente tener una única variable de estado que contenga un objeto que una variable de estado por campo. [Elegir la estructura del estado](/learn/choosing-the-state-structure) tiene más consejos sobre esto.
```
La [traducción directa del gerundio](https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#el-gerundio) con función sustantiva en los títulos podría perder significado, por eso es recomendado utilizar un infinitivo (Eligiendo->Elegir).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +> La sintáxis de `[` y `]` se le conoce cómo [destructuración del array](https://javascript.info/destructuring-assignment) y es lo que permite leer los valores de un array. El array retornado por `us
```suggestion
> A la sintaxis de `[` y `]` se le conoce cómo [desestructuración de un array](https://javascript.info/destructuring-assignment) y permite leer valores de un array. El array retornado por `useState` siempre contará con exactamente dos valores.
```

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +Los *Hooks* son funciones especiales que sólo están disponibles mientras React está [renderizando](/learn/render-and-commit#step-1-trigger-a-render) (algo que veremos con más detalle en la página sig
```suggestion
Los *Hooks* son funciones especiales que sólo están disponibles mientras React está [renderizando](/learn/render-and-commit#step-1-trigger-a-render) (algo que veremos con más detalle en la página siguiente). Los Hooks permiten "engancharnos" a diferentes características de React.
```
Razón: Al usar ya el término "funciones" antes, podría tender a la confusión el usar tal palabra otra vez, si usamos "funcionalidades", o "características" por ejemplo, podemos mantener el sentido y a la vez evitar la confusión para la gente nueva en React, además, así mantenemos la consistencia con la traducción de la palabra en la siguiente línea "El estado es solo una de esas características,".

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +**Las funciones-Hook que empiecen con `use` deben ser solo llamadas en el nivel superior de los componentes o [en tus propios Hooks.](/learn/reusing-logic-with-custom-hooks)** No podemos usar Hooks d
```suggestion
**Las funciones-Hook que empiecen con `use` deben ser solo llamadas en el nivel superior de los componentes o [en tus propios Hooks.](/learn/reusing-logic-with-custom-hooks)** No podemos usar Hooks dentro de condicionales, bucles, u otras funciones anidadas. Los Hooks son funciones, pero es útil pensar en ellos como declaraciones independientes de las necesidades de nuestro componente. Las funciones de React se "usan" en la parte superior del componente de manera similar a cómo se "importan" módulos en la parte superior de un archivo.
```
Está un poco difícil la traducción, pero cambiando un poco las palabras podemos mantener el significado de la oración original, al usar incondicional->independiente podemos mantener el sentido de que no debemos cambiar el lugar en el que ejecutamos el hook dependiendo de nuestras necesidades, como declarar estados debido a condicionales, o dentro de mapeos, try...catch, declaraciones de funciones, etc, ya que si hacemos eso, entonces React perderá el orden y/o cantidad en su array de arrays [getter, setter] de nuestros estados (si no están en top level, el call stack no te queda de la misma manera)

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +> La convención es nombrar estas dos variables como `const [algo, establecerAlgo]`. Podemos nombrarlo como queramos, pero mantener las convenciones hacen que las cosas sean más fáciles de entender en
```suggestion
> La convención es nombrar estas dos variables como `const [algo, setAlgo]`. Podemos nombrarlo como queramos, pero mantener las convenciones hacen que las cosas sean más fáciles de entender en todos los proyectos.
```
Razón: La convención que se usa comúnmente es [estado, setEstado] (o [estado, setEstado]), al usar "establecerAlgo", estamos perdiendo la convención de usar el prefijo de "set" para hacer alusión al setter (porque devuelve un array con un [getter, setter]).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +1. La **variable de estado** (`index`) con el valor que almacenó.
```suggestion
1. La **variable de estado** (`index`) con el valor que almacenaste.
```
Razón: Solemos usar la [segunda persona singular "tú"](https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#usted-t%C3%BA-y-vos) para mantener el tono informal de la documentación original.

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +1. **Tu componente se renderiza la primera vez.** Debido a que pasamos `0` a `useState` como valor inicial para `index`, esto devolverá `[0, setIndex]`. React recuerda que `0` es el último valor de e
```suggestion
1. **Tu componente se renderiza por primera vez.** Debido a que pasamos `0` a `useState` como valor inicial para `index`, esto devolverá `[0, setIndex]`. React recuerda que `0` es el último valor de estado.
```

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
>          by {sculpture.artist}
```suggestion
        por {sculpture.artist}
```
Razón: Así mantenemos la traducción de strings al español de manera consistente (la idea es mantenerlo en inglés, o en español, pero no ambas).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
>          by {sculpture.artist}
```suggestion
        por {sculpture.artist}
```
Razón: Así mantenemos la traducción de strings al español de manera consistente (la idea es mantenerlo en inglés, o en español, pero no ambas).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +También observemos cómo el componente de `Página` no "sabe" nada sobre el estado del componente `Galería` o incluso si tiene algún estado. A diferencia de las props, **el estado es totalmente privado
```suggestion
También observemos cómo el componente de la página `Page` no "sabe" nada sobre el estado del componente de la galería `Galery`, ni siquiera si es que posee algún estado. A diferencia de las props, **el estado es totalmente privado para el componente que lo declara.** El componente padre no puede cambiarlo. Esto permite agregar el estado a cualquier componente o eliminarlo sin afectar al resto de los componentes.
```
Razón: De tal manera podemos mantener la consistencia y hacer referencia a lo mismo tanto en la explicación como en el _CodeSandBox_ a lo largo del capítulo (En el código no fue traducido el nombre del componente).

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +* El Hook `useState` retorna un arreglo de dos valores: el estado actual y la función para actualizarlo.
```suggestion
* El Hook `useState` retorna un *array* de dos valores: el estado actual y la función para actualizarlo.
```
Razón: Así mantenemos la consistencia con los usos anteriores y posteriores en este capítulo, y los capítulos anteriores en la documentación.

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +* Los Hooks se importan de la siguiente manera: deben llamarse incondicionalmente. Llamar Hooks, incluido `useState`, solo es válido en el nivel superior de un componente u otro Hook.
```suggestion
*Evita llamar a Hooks de manera anidada (por ejemplo, dentro de bucles o condicionales). Llamar a Hooks -incluyendo al useState- solo es válido en el nivel superior de un componente u otro Hook.
```
Razón: La traducción directa pierde algo de significado, por lo que podemos cambiar algunas palabras para mantenerlo en español.

2022-10-29 22:58 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +Cada vez que el componente se renderiza, el `useState` devuelve una matriz que contiene dos valores:
```suggestion
Cada vez que el componente se renderiza, el `useState` devuelve un *array* que contiene dos valores:
```
Razón: Así mantenemos la consistencia con los usos anteriores y posteriores en este capítulo, y los capítulos anteriores en la documentación.

2022-10-30 20:36 UTC, samarjaffal commented on beta/src/content/learn/state-a-components-memory.md
> +2. Una **función que setea el estado** para actualizar la variable y provocar que React renderice el componente nuevamente.
Realmente a mí también me gusta más el termino de setear. De todos modo quedo atenta a lo que ustedes decidan qué es lo mejor.

2022-10-30 20:39 UTC, samarjaffal commented
Hola @Vicenciomf1  
¡Muchas gracias por las sugerencias y correcciones!
Voy a estar actualizando mi rama con las correcciones y tan pronto las tenga listas, les aviso.

Y muchas gracias por ver mi charla, significa mucho para mí 🤗

2022-10-31 00:27 UTC, samarjaffal commented
@Vicenciomf1 Creo que ya hice todas las sugerencias que me colocaste. Estoy a la espera de saber si seguiremos usando la palabra "setear". Espero no se me haya pasado nada :)

2022-10-31 01:21 UTC, Vicenciomf1 commented
> @Vicenciomf1 Creo que ya hice todas las sugerencias que me colocaste. Estoy a la espera de saber si seguiremos usando la palabra "setear". Espero no se me haya pasado nada :)

Hola @samarjaffal! Revisé en [MDN](https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Working_with_Objects#definici%C3%B3n_de_captadores_getters_y_establecedores_setters) y en [diversas ocasiones](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Functions/set#definiendo_un_setter_en_el_inicializador_de_nuevos_objetos) se ocupa tal término, por lo que no sería algún caso aislado que tú o yo hayamos interiorizado tal término en vez de establecedor o asignador, con respecto a la [documentación anterior, se evita la traducción y sólo se le llama función](https://es.reactjs.org/docs/hooks-reference.html#usestate), si @carburo está de acuerdo, puedo modificar las veces en las que se utilizó "asignadora" en el [capítulo de las refs](https://beta.es.reactjs.org/learn/referencing-values-with-refs#differences-between-refs-and-state) y agregarlo al glosario en la guía de estilos como "*setter*" a tal función, y "asignar" a "set", sería sólo eso y hacemos el merge.

Pd: Agregué unas cositas mínimas, pero está todo perfecto! Muchas gracias por tu aporte

Pd2: No hay nada que agradecer, cuando se hacen las cosas de tal manera, lo bueno llega solo (a mí parecer), y efectivamente haces "un impacto en la vida de los demás", además es un orgullo el que alguien hable de temas que mejoran la salud mental y el ambiente laboral, casi siempre la gente se enfoca sólo en lo técnico.

2022-10-31 02:31 UTC, carburo commented
@Vicenciomf1 
Creo que podemos postergar la decisión sobre esa terminología para no bloquear el PR. Podríamos crear posteriormente un hilo de debate para analizarlo. Después de todo la documentación aún está en beta y podemos aplicar luego lo que se decida a las páginas que ya están traducidas. Es importante mantener consistente la terminología en este caso porque en la nueva documentación a menudo se hace la distinción entre _setting the state_ vs. _updating the state_ y esa misma distinción debe quedar clara en las traducciones.

2022-10-31 04:07 UTC, Vicenciomf1 approved these changes
¡Listo! Lo tendré anotado entonces para que sea más fácil hacer las modificaciones en el futuro cuando se llegue a un consenso acerca del término :)

2022-10-31 04:10 UTC, Vicenciomf1 commented
¡Gracias @samarjaffal y @carburo!

2022-10-31 04:13 UTC, merged

2022-10-31 13:24 UTC, samarjaffal commented
Gracias a ustedes 🤗 @Vicenciomf1 @carburo

2022-10-31 15:08 UTC, bonavida commented on beta/src/content/learn/state-a-components-memory.md
> +title: "El Estado: Como memoria de un componente"
@Vicenciomf1 ¿Por qué ha desaparecido la preposición "de" del título? En mi humilde opinión, sin ella, la frase deja de tener sentido. Debería ser "El estado: La memoria de un componente".

2022-10-31 16:09 UTC, Vicenciomf1 commented on beta/src/content/learn/state-a-components-memory.md
> +title: "El Estado: Como memoria de un componente"
Hola @bonavida! Tienes toda la razón, sinceramente no sé cómo esa pertenencia se me fue, generalmente reviso hartas veces antes de hacer alguna sugerencia (probablemente sea debido a que hice dos comentarios, y copié y pegué el anterior para usar los _suggested changes_ de Github en el nuevo comentario).

Actualmente tengo una lista con muchos _typos_ de este tipo, pienso presentarlos todos en un PR, probablemente veas los cambios en máximo una semana. ¡Muchas gracias por tu comentario!
P. D: No te preocupes por comentar la rama mergeada, sinceramente no lo hubiese notado sin aquél, así que muchas gracias.