Translate useLayoutEffect
reactjs/es.reactjs.org pull request #626
Opened 2023-02-07 05:29 UTC by luiserdef

#500

2023-03-24 14:56 UTC, carburo requested changes

2023-03-24 14:56 UTC, carburo commented on beta/src/content/reference/react/useLayoutEffect.md
> +* `setup`: La función con la lógica de tu Efecto. Tu función setup puede retornar opcionalmente una función de *limpieza*. Antes que tu componente sea agregado primeramente al DOM, react va a ejecuta
```suggestion
* `setup`: La función con la lógica de tu Efecto. Tu función setup puede retornar opcionalmente una función de *limpieza*. Antes que tu componente sea agregado primeramente al DOM, React va a ejecutar tu función setup. Después de cada renderizado con dependencias modificadas, React primero va a ejecutar la función de limpieza (si tú lo provees) con los valores anteriores, y luego ejecuta tu función setup con los nuevos valores. Antes que tu componente sea eliminado del DOM, React va a ejecutar tu función de limpieza una última vez.
```

2023-03-24 14:56 UTC, carburo commented on beta/src/content/reference/react/useLayoutEffect.md
> +En el [ejemplo del principio](#measuring-layout-before-the-browser-repaints-the-screen), `useLayoutEffect` llama al componente `tooltip`, se posiciona a si mismo correctamente (ya sea arriba o debajo
```suggestion
En el [ejemplo del principio](#measuring-layout-before-the-browser-repaints-the-screen), `useLayoutEffect` llama al componente `Tooltip`, se posiciona a sí mismo correctamente (ya sea arriba o debajo del contenido) dependiendo de la altura del contenido. Si trataras de renderizar `Tooltip` como parte del HTML inicial del servidor, esto sería imposible de determinar. ¡En el servidor no hay navegador ni layout! Incluso si lo renderizas en el servidor, su posición "saltará" en el cliente después de que el código JavaScript cargue y se ejecute.
```

2023-03-24 14:56 UTC, carburo commented on beta/src/content/reference/react/useLayoutEffect.md
> +Sin embargo, si estas pasando por este problema, tienes algunas opciones:
```suggestion
Sin embargo, si estás pasando por este problema, tienes algunas opciones:
```

2023-03-24 14:56 UTC, carburo commented on beta/src/content/reference/react/useLayoutEffect.md
> +1. Puedes reemplazar `useLayoutEffect` con [`useEffect`.](/reference/react/useEffect) Este le dice a React que está bien mostrar el resultado inicial del renderizado sin bloquear el pintado (porque e
```suggestion
1. Puedes reemplazar `useLayoutEffect` con [`useEffect`.](/reference/react/useEffect) Esto le dice a React que está bien mostrar el resultado inicial del renderizado sin bloquear el pintado (porque el HTML original se convierte en visible antes que tu Efecto se ejecute).
```

2023-03-24 14:56 UTC, carburo commented on beta/src/content/reference/react/useLayoutEffect.md
> +2. Puedes [marcar tu componente como solo cliente.](/reference/react/Suspense#providing-a-fallback-for-server-errors-and-server-only-content) Este le dice a React de reemplazar su contenido hasta la
```suggestion
2. Puedes [marcar tu componente como solo cliente.](/reference/react/Suspense#providing-a-fallback-for-server-errors-and-server-only-content) Esto le indica a React que debe reemplazar su contenido hasta la barrera de [`<Suspense>`](/reference/react/Suspense) más cercana con un *fallback* de carga (por ejemplo, un spinner o un glimmer) durante el renderizado en el lado del servidor)
```

2023-03-24 14:56 UTC, carburo commented on beta/src/content/reference/react/useLayoutEffect.md
> +3. Puedes mostrar diferentes componentes en el servidor y en el cliente. Una manera de hacer esto es mantener el estado booleano `isMounted` que está inicializado en `falso`, y cambiarlo a `verdadero
```suggestion
3. Puedes mostrar diferentes componentes en el servidor y en el cliente. Una manera de hacer esto es mantener el estado booleano `isMounted` que está inicializado en `false`, y cambiarlo a `true` dentro de la llamada de un `useEffect`. La lógica de renderizado puede ser entonces como `return isMounted ? <RealContent /> : <FallbackContent />`. En el servidor y durante la hidratación, el usuario va a ver `FallbackContent` que no debe llamar `useLayoutEffect`. Luego React va a reemplazarlo con `RealContent` que se ejecuta solo en el lado del cliente y puede incluir llamadas a `useLayoutEffect`.
```

2023-03-24 14:56 UTC, carburo commented on beta/src/content/reference/react/useLayoutEffect.md
> +4. Si sincronizas tu componente con un almacén externo de datos y depende de `useLayoutEffect`  por diferentes razones que medir el layout, considera en su lugar usar [`useSyncExternalStore`](/refere
```suggestion
4. Si sincronizas tu componente con un almacén externo de datos y dependes de `useLayoutEffect`  por diferentes razones que medir el layout, considera en su lugar usar [`useSyncExternalStore`](/reference/react/useSyncExternalStore) que [soporta renderizado del lado del servidor.](/reference/react/useSyncExternalStore#adding-support-for-server-rendering)
```

2023-03-24 15:07 UTC, carburo approved these changes
¡Gracias! Solo hice unas pequeñas correcciones sobre todo con la conjugación de la segunda persona del singular de acuerdo a la guía de estilo (https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#usted-tú-y-vos).

2023-03-24 15:13 UTC, carburo requested changes
¡Gracias por tu contribución! He dejado algunos comentarios para que revises.

2023-03-25 01:43 UTC, luiserdef commented on beta/src/content/reference/react/useLayoutEffect.md
> +* Cuando el modo estricto está activado, React va a **ejecutar un setup adicional solo para desarrollo + ciclo de limpieza**  antes del primer setup real. Esta es una prueba de estrés que asegura que
Corregí esta parte en el último commit (habia un espacio extra que no debe estar después de _**ciclo de limpieza****_ )

2023-03-25 01:52 UTC, luiserdef commented
Me sorprendió las faltas de ortografía que se me escaparon. Ya he realizado los cambios que me has sugerido por lo que ahora debería estar todo en orden.

2023-03-28 22:14 UTC, carburo approved these changes
:rocket:

2023-03-28 22:15 UTC, merged