Adding translations to the startTransition API
reactjs/es.reactjs.org pull request #631
Opened 2023-02-18 15:10 UTC by RubenChirino

[#500](https://github.com/reactjs/es.reactjs.org/issues/500)

2023-03-28 22:46 UTC, carburo requested changes
¡Hola! ¡Gracias por tu contribución! Te he dejado algunos comentarios antes de mezclar el PR. Todos están en forma de sugerencias de GitHub que puedes aplicar o en caso que estés en desacuerdo, puedes dejar comentar en ese mismo lugar. La mayor parte son relacionados con el uso de «usted» para la segunda persona del singular. Para mantener la consistencia en la documentación y porque es menos propenso a ambigüedades hemos optado por usar siempre «tú» (Puedes consultar nuestra [guía de traducción](https://github.com/reactjs/es.reactjs.org/blob/master/TRANSLATION.md#style-guide) para otros aspectos como este).

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +La función `startTransition` le permite marcar una actualización de estado como una transición.
```suggestion
La función `startTransition` te permite marcar una actualización de estado como una transición.
```

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +* `startTransition` no proporciona una forma de rastrear si hay una transición pendiente. Para mostrar un indicador pendiente mientras se produce la transición, debe utilizar [`useTransition`](/refer
```suggestion
* `startTransition` no proporciona una forma de rastrear si hay una transición pendiente. Para mostrar un indicador pendiente mientras se produce la transición, debes utilizar [`useTransition`](/reference/react/useTransition) en su lugar.
```

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +* Solo puede envolver una actualización en una transición si tiene acceso a la función `set`  de ese estado. Si desea iniciar una transición en respuesta a alguna propiedad o un valor de retorno pers
```suggestion
* Solo puedes envolver una actualización en una transición si tienes acceso a la función `set`  de ese estado. Si deseas iniciar una transición en respuesta a alguna prop o un valor de retorno de un Hook personalizado, intenta usar [`useDeferredValue`](/reference/react/usedeferredvalue) en su lugar.
```

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +* La función que pasa a `startTransition` debe ser sincrónica. React ejecuta inmediatamente esta función, marcando todas las actualizaciones de estado que ocurren mientras se ejecuta como transicione
```suggestion
* La función que pasas a `startTransition` debe ser sincrónica. React ejecuta inmediatamente esta función, marcando todas las actualizaciones de estado que ocurren mientras se ejecuta como transiciones. Si intentas realizar más actualizaciones de estado más tarde (por ejemplo, en un timeout), no se marcarán como transiciones.
```

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +* Una actualización de estado marcada como una transición será interrumpida por otras actualizaciones de estado. Por ejemplo, si actualiza un componente de gráfico dentro de una transición, pero lueg
Creo que sería preferible desambiguar «entrada», pues puede no ser tan claro su uso en este contexto en español.

```suggestion
* Una actualización de estado marcada como una transición será interrumpida por otras actualizaciones de estado. Por ejemplo, si actualizas un componente de gráfico dentro de una transición, pero luego comienzas a escribir en una entrada de texto mientras el gráfico está en medio de una rerenderización, React reiniciará el trabajo de renderizado en el componente de gráfico después de manejar la actualización de estado de la entrada de texto.
```

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +Puede marcar una actualización de estado como una transición envolviéndola en una llamada `startTransition`:
```suggestion
Puedes marcar una actualización de estado como una transición envolviéndola en una llamada `startTransition`:
```

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +`startTransition` es muy similar a [`useTransition`](/reference/react/useTransition), excepto que no proporciona la bandera `isPending` para rastrear si una transición está en curso. Puede llamar a `
```suggestion
`startTransition` es muy similar a [`useTransition`](/reference/react/useTransition), excepto que no proporciona la bandera `isPending` para rastrear si una transición está en curso. Puedes llamar a `startTransition` cuando `useTransition` no esté disponible. Por ejemplo, `startTransition` funciona fuera de los componentes, como desde una biblioteca de datos.
```

2023-03-28 22:46 UTC, carburo commented on beta/src/content/reference/react/startTransition.md
> +[Aprenda sobre las transiciones y vea ejemplos en la página de `useTransition`.](/reference/react/useTransition)
```suggestion
[Aprende sobre las transiciones y ve ejemplos en la página de `useTransition`.](/reference/react/useTransition)
```

2023-04-01 14:35 UTC, RubenChirino commented
Gracias @carburo por las correciones, lo tendré en cuenta para las proximas! He tomado todos tus aportes.

2023-04-02 00:46 UTC, carburo approved these changes
:rocket:

2023-04-02 00:47 UTC, merged