Adding translations to the <Profiler> component
reactjs/es.reactjs.org pull request #633
Opened 2023-02-25 16:09 UTC by RubenChirino

[#500](https://github.com/reactjs/es.reactjs.org/issues/500)

2023-03-18 21:13 UTC, javierlopezdeancos commented on beta/src/content/reference/react/Profiler.md
> +`<Profiler>` te permite medir el rendimiento de la performance de un árbol de React de forma programática.
```suggestion
`<Profiler>` te permite medir el rendimiento de la performance de un árbol de componentes de React de forma programática.
```

2023-03-18 21:14 UTC, javierlopezdeancos commented on beta/src/content/reference/react/Profiler.md
> +* `id`: Un string que identifica la parte de la interfaz de usuario que se está midiendo.
```suggestion
* `id`: Un string que identifica que parte de la interfaz de usuario estas midiendo.
```

2023-03-28 22:59 UTC, carburo requested changes
¡Hola! ¡Gracias por tu contribución! Te he dejado algunos comentarios que deben revisarse antes de mezclar el PR. Todos están en forma de sugerencias de GitHub que puedes aplicar o en caso que estés en desacuerdo, puedes dejar comentar en ese mismo lugar.

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +`<Profiler>` te permite medir el rendimiento de la performance de un árbol de componentes de React de forma programática.
```suggestion
`<Profiler>` te permite medir el rendimiento del renderizado de un árbol de componentes de React de forma programática.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +* `id`: Un string que identifica qué parte de la interfaz de usuario estas midiendo.
```suggestion
* `id`: Un string que identifica qué parte de la interfaz de usuario estás midiendo.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +* `onRender`: Una [devolución de llamada `onRender`](#onrender-callback) que React llama cada vez que los componentes dentro del árbol perfilado se actualizan. Recibe información sobre lo que se rend
https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#style-guide
```suggestion
* `onRender`: Un [*callback* `onRender`](#onrender-callback) que React llama cada vez que los componentes dentro del árbol perfilado se actualizan. Recibe información sobre lo que se renderizó y cuánto tiempo llevó.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +* El perfilado agrega cierta sobrecarga adicional, por lo que **está deshabilitado en la versión de producción de manera predeterminada.** Para optar por el perfilado en producción, debe habilitar un
https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#usted-tú-y-vos
```suggestion
* El perfilado agrega cierta sobrecarga adicional, por lo que **está deshabilitado en la versión de producción de manera predeterminada.** Para optar por el perfilado en producción, debes habilitar una [versión especial de producción con el perfilado habilitado.](https://fb.me/react-profiling)
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +React llamará su devolución de llamada `onRender` con información sobre lo que se renderizó.
```suggestion
React llamará tu *callback* `onRender` con información sobre lo que se renderizó.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +* `id`: La propiedad `id` del árbol `<Profiler>` que acaba de ser entregado.  Esto te permite identificar qué parte del árbol se entregó si estás usando varios perfiles.
https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#traducciones-comunes
```suggestion
* `id`: La prop `id` del árbol `<Profiler>` que acaba de ser entregado.  Esto te permite identificar qué parte del árbol se entregó si estás usando varios perfiles.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +* `actualDuration`: El número de milisegundos que se tardó en renderizar el árbol `<Profiler>` Esto indica qué tan bien el subárbol hace uso de la memorización (por ejemplo, [`memo`](/reference/react
```suggestion
* `actualDuration`: El número de milisegundos que se tardó en renderizar el árbol `<Profiler>` Esto indica qué tan bien el subárbol hace uso de la memoización (por ejemplo, [`memo`](/reference/react/memo) y [`useMemo`](/reference/react/useMemo)). Idealmente, este valor debería disminuir significativamente después del montaje inicial, ya que muchos de los descendientes solo necesitarán volver a renderizarse si cambian sus propiedades específicas.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +* `baseDuration`: El número de milisegundos que estima cuánto tiempo tardaría en volver a renderizar todo el subárbol `<Profiler>` sin ninguna optimización. Se calcula sumando las duraciones de rende
```suggestion
* `baseDuration`: El número de milisegundos que estima cuánto tiempo tardaría en volver a renderizar todo el subárbol `<Profiler>` sin ninguna optimización. Se calcula sumando las duraciones de renderizado más recientes de cada componente en el árbol. Este valor estima el costo del renderizado para el peor de caso (por ejemplo, el montaje inicial o un árbol sin memoización). Compara `actualDuration` con este valor para ver si la memorización está funcionando.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +### Medición del rendimiento de la performance programáticamente {/*measuring-rendering-performance-programmatically*/}
```suggestion
### Medición del rendimiento de renderizado programáticamente {/*measuring-rendering-performance-programmatically*/}
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +Envuelve el componente `<Profiler>` alrededor de un árbol de React para medir su rendimiento de performance.
```suggestion
Envuelve el componente `<Profiler>` alrededor de un árbol de React para medir su rendimiento de renderizado.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +Se requieren dos props: un `id` (string) y un callback `onRender` (function) que React llama cada vez que un componente dentro del árbol "comete" una actualización.
```suggestion
Se requieren dos props: un `id` (string) y un *callback* `onRender` (function) que React llama cada vez que un componente dentro del árbol "comete" una actualización.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +`<Profiler>` te permite recopilar mediciones de forma programática.  Si estás buscando un perfilador interactivo, prueba la pestaña Profiler en las [React Developer Tools](/learn/react-developer-tool
- Usar texto traducido de la sección https://beta.es.reactjs.org/learn/react-developer-tools
```suggestion
`<Profiler>` te permite recopilar mediciones de forma programática.  Si estás buscando un perfilador interactivo, prueba la pestaña Profiler en las [Herramientas de Desarrollo de React](/learn/react-developer-tools). Expone funcionalidades similares a una extensión del navegador.
```

2023-03-28 22:59 UTC, carburo commented on beta/src/content/reference/react/Profiler.md
> +### Midiendo diferentes partes de la aplicación {/*measuring-different-parts-of-the-application*/}
https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#el-gerundio
```suggestion
### Medición de diferentes partes de la aplicación {/*measuring-different-parts-of-the-application*/}
```

2023-04-01 14:43 UTC, RubenChirino commented
Gracias @carburo y @javierlopezdeancos, he tomado sus cambios para mejorar las traducciones 🙌.

2023-04-01 17:29 UTC, javierlopezdeancos commented
Gracias a ti

2023-04-02 00:49 UTC, carburo approved these changes

2023-04-02 00:49 UTC, merged