Textarea documentation translation
reactjs/es.reactjs.org pull request #636
Opened 2023-03-04 01:07 UTC by manuelrodgzz

#500
Además de la traducción de la documentación del textarea, también agregué la traducción del termino _bubbling_ de acuerdo a la siguiente discusión #635 .

2023-03-29 02:52 UTC, carburo requested changes
¡Hola! ¡Gracias por tu contribución! Te he dejado algunos comentarios que deben revisarse antes de mezclar el PR. Todos están en forma de sugerencias de GitHub que puedes aplicar o en caso que estés en desacuerdo, puedes dejar comentar en ese mismo lugar.

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +* [`form`](https://developer.mozilla.org/es/docs/Web/HTML/Element/textarea#attr-form): Un string. Especifica el `id` del `<form>` al que este input pertenece. Si es omitido, es el formulario padre ma
```suggestion
* [`form`](https://developer.mozilla.org/es/docs/Web/HTML/Element/textarea#attr-form): Un string. Especifica el `id` del `<form>` al que este input pertenece. Si es omitido, es el formulario padre más cercano.
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +Típicamente, colocarás todos los `<textarea>` dentro de una etiqueta [`<label>`](https://developer.mozilla.org/es/docs/Web/HTML/Element/label). Esto le indica al navegador que este label está asociad
```suggestion
Típicamente, colocarás todos los `<textarea>` dentro de una etiqueta [`<label>`](https://developer.mozilla.org/es/docs/Web/HTML/Element/label). Esto le indica al navegador que este label está asociado con ese text area. Cuando el usuario haga click en el label, el navegador enfocará el text area. Esto también es esencial para accesibilidad: un lector de pantallas anunciará el texto del label cuando el usuario enfoque el text area.
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +Si no puedes anidar el `<textarea>` dentro de un `<label>`, asociales pasando el mismo identificador a `<textarea id>` y [`<label htmlFor>`.](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabe
```suggestion
Si no puedes anidar el `<textarea>` dentro de un `<label>`, asócialos pasando el mismo identificador a `<textarea id>` y [`<label htmlFor>`.](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/htmlFor) Para evitar conflictos entre instancias de un componente, genera un identificador con [`useId`.](/reference/react/useId)
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> + Agrega un [`<form>`](https://developer.mozilla.org/es/docs/Web/HTML/Element/form) alrededor de tu text area con un [`<button type="submit">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Elemen
```suggestion
 Agrega un [`<form>`](https://developer.mozilla.org/es/docs/Web/HTML/Element/form) alrededor de tu text area con un [`<button type="submit">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit) dentro. Este llamará a tu manejador de evento `<form onSubmit>`. Por defecto, el navegador enviará los datos del formulario a el URL actual y actualizará la página. Puedes sobrescribir ese comportamiento llamando `e.preventDefault()`. Para leer los datos del formulario, usa [`new FormData(e.target)`](https://developer.mozilla.org/es/docs/Web/API/FormData).
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +export default function NuevoPost() {
https://github.com/reactjs/es.reactjs.org/blob/main/TRANSLATION.md#texto-en-bloques-de-código
No hay necesariamente nada incorrecto en traducir fragmentos de código, siempre que no sean APIs existentes (del navegador, React, etc.), sin embargo como parte del mantenimiento es problemático porque suelen generar muchos conflictos cuando ocurren actualizaciones en el artículos.
```suggestion
export default function NewPost() {
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +export default function Formulario() {
```suggestion
export default function Form() {
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +export default function EditarPost() {
```suggestion
export default function EditPost() {
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +  const [contenidoPost, asignaContenidoPost] = useState(''); // Declara una variable de estado...
También queremos preservar la convención [value, setValue] en las variables de useState.
```suggestion
function NewPost() {
  const [postContent, setPostContent] = useState(''); // Declara una variable de estado...
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +      onChange={e => asignaContenidoPost(e.target.value)} // ... ¡y actualiza la variable de estado con cada cambio!
```suggestion
      value={postContent} // ...fuerza al valor del input a que coincida con la variable de estado...
      onChange={e => setPostContent(e.target.value)} // ... ¡y actualiza la variable de estado con cada cambio!
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +  const [contenidoPost, asignaContenidoPost] = useState('_Hola,_ **Markdown**!');
```suggestion
export default function MarkdownEditor() {
  const [postContent, setPostContent] = useState('_Hola,_ **Markdown**!');
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +          onChange={e => asignaContenidoPost(e.target.value)}
```suggestion
          value={postContent}
          onChange={e => setPostContent(e.target.value)}
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +export default function EditarPost() {
```suggestion
export default function EditPost() {
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +  const htmlRenderizado = md.render(markdown);
```suggestion
  const renderedHTML = md.render(markdown);
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +  return <div dangerouslySetInnerHTML={{__html: htmlRenderizado}} />;
```suggestion
  return <div dangerouslySetInnerHTML={{__html: renderedHTML}} />;
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +  asignaPrimerNombre(e.target.value.toUpperCase());
```suggestion
  setFirstName(e.target.value.toUpperCase());
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +    asignaPrimerNombre(e.target.value);
```suggestion
    setFirstName(e.target.value);
```

2023-03-29 02:52 UTC, carburo commented on beta/src/content/reference/react-dom/components/textarea.md
> +  asignaPrimerNombre(e.target.value);
```suggestion
  setFirstName(e.target.value);
```

2023-04-01 22:49 UTC, manuelrodgzz commented
@carburo muchas gracias por revisar mi PR! he realizado los cambios que sugeriste 😄

2023-04-02 00:43 UTC, carburo approved these changes
¡Gracias!

2023-04-02 00:44 UTC, merged