Translate input reference
reactjs/es.reactjs.org pull request #641
Opened 2023-03-07 03:40 UTC by Guirdo

Hola. Estoy atento a cualquier corrección.

2023-03-31 00:57 UTC, carburo requested changes
¡Hola! ¡Gracias por tu contribución! Dejé algunas sugerencias de cambios que puedes aplicar o comentar si no estás de acuerdo. Sin embargo, esta es una revisión preliminar. No he terminado de revisar porque he notado algunas cuestiones que se repiten en varios lugares del documento y que nos ayudaría si las revisaras primero:

- El uso de «usted» para la segunda persona del singular. Para mantener la consistencia en la documentación y porque es menos propenso a ambigüedades hemos optado por usar siempre «tú» (Puedes consultar nuestra [guía de traducción](https://github.com/reactjs/es.reactjs.org/blob/master/TRANSLATION.md#style-guide) para otros aspectos como este).
- Uso de prop como nombre masculino en lugar de femenino como se indica en la guía de traducción (como acortamiento de propiedad).
* Se repiten algunas erratas y errores que podrían ser detectadas por una herramienta automática (por ejemplo, para VSCode puedes usar [esta](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-spanish)).

Una vez que termines puedes solicitar una nueva revisión.

2023-04-05 23:25 UTC, Guirdo commented
Gracias por la sugerencias. He arreglado los typos que señalaste y otros que se me pasaron la primera vez.

2023-04-06 01:26 UTC, carburo approved these changes

2023-04-06 01:28 UTC, merged

2023-04-06 01:28 UTC, carburo commented
¡Gracias!