renderToNodeStream translation
reactjs/es.reactjs.org pull request #646
Opened 2023-03-22 17:01 UTC by cosmoart

#500 Traducción de renderToNodeStream

Me tome la libertad de traduccir "Node.js Readable Stream" como "*Stream* legible de Node.js."

2023-03-31 20:12 UTC, carburo requested changes
¡Hola! ¡Gracias por tu contribución! Te he dejando algunos comentarios y sugerencias para que revises antes de que mezclemos este PR.

2023-03-31 22:41 UTC, cosmoart commented on beta/src/content/reference/react-dom/server/renderToNodeStream.md
> +`renderToNodeStream` renderiza un árbol de React en un [*Stream* legible de Node.js.](https://nodejs.org/api/stream.html#readable-streams)
Mis opciones de traducción fueron «Flujo legible de Node.js» y  «*Stream* legible de Node.js». Elegí la segunda opción porque:
- En varias publicaciones en español se usan ambos términos. Como en [esta](https://desarrolloweb.com/articulos/streams-nodejs.html) o [esta](https://www.freecodecamp.org/espanol/news/node-js-streams-todo-lo-que-necesitas-saber/).
- En Node.js estoy más familiarizado con el termino "Stream" que "Flujo".

2023-04-02 00:39 UTC, carburo commented on beta/src/content/reference/react-dom/server/renderToNodeStream.md
> +`renderToNodeStream` renderiza un árbol de React en un [*Stream* legible de Node.js.](https://nodejs.org/api/stream.html#readable-streams)
> En varias publicaciones en español se usan ambos términos. Como en [esta](https://desarrolloweb.com/articulos/streams-nodejs.html) o [esta](https://www.freecodecamp.org/espanol/news/node-js-streams-todo-lo-que-necesitas-saber/).

Sí, el hecho de que no haya una consenso sobre qué término usar es el principal punto de mi comentario original
Seguramente será uno de los términos a revisitar luego de que se hayan hecho todas las traducciones para lograr una consistencia entre las diversas páginas de la documentación. De momento me parece bien y creo que podemos mezclar los cambios así.

2023-04-02 00:39 UTC, carburo approved these changes

2023-04-02 00:40 UTC, merged